# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b407a8d4f5cd4f609e951eadde917b5bddd43f1907f413a6436e08e04777e6d4855cb98f9feef32efb373662cdd481ddb954ad9be859a1acecf226b155f837

test:
  secret_key_base: bf8be1cccc5b86f54fc287237caec4ee48ba892f8c26d6be640723a343343030d923da91ee08f0d82e74d714cc9208257b37ae58bf80661315c55a69efd0121b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
